import { create, NAlert, NButton, NCard, NCheckbox, NCollapse, NCollapseItem, NDataTable, NDrawer, NDrawerContent, NDropdown, NForm, NFormItem, NGradientText, NIcon, NInput, NInputNumber, NLayout, NLayoutContent, NLayoutHeader, NList, NListItem, NMenu, NModal, NPageHeader, NSelect, NSkeleton, NSpace, NSplit, NSwitch, NTabPane, NTabs, NTag, NThing, NTime, NTooltip, NTreeSelect, NUpload } from 'naive-ui';

export const naive = create({
  components: [
    NAlert,
    NButton,
    NCard,
    NCheckbox,
    NCollapse,
    NCollapseItem,
    NDataTable,
    NDrawer,
    NDrawerContent,
    NDropdown,
    NForm,
    NFormItem,
    NGradientText,
    NIcon,
    NInput,
    NInputNumber,
    NLayout,
    NLayoutContent,
    NLayoutHeader,
    NList,
    NListItem,
    NMenu,
    NModal,
    NPageHeader,
    NSelect,
    NSkeleton,
    NSpace,
    NSplit,
    NSwitch,
    NTabPane,
    NTabs,
    NTag,
    NThing,
    NTime,
    NTooltip,
    NTreeSelect,
    NUpload,
  ],
});
