name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            package-script: npm run package:linux
            artifact-name: testrun-linux
            artifact-glob: release/*.AppImage
          - os: macos-latest
            target: mac
            package-script: npm run package:mac
            artifact-name: testrun-mac
            artifact-glob: release/*.dmg
          - os: windows-latest
            target: win
            package-script: npm run package:win
            artifact-name: testrun-win
            artifact-glob: release/*.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '0'

      - name: Prepare database
        run: npm run db:prepare

      - name: Typecheck
        run: npm run typecheck

      - name: Run Playwright tests
        run: npm run playwright:test
        env:
          CI: 'true'

      - name: Package application
        run: ${{ matrix.package-script }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-glob }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
